### ISSUE TITLE
Publish 0.7.0 release 

### ISSUE THREAD

**Issue by sabbyanandan** [spring-projects/spring-flo#16]
As a developer, I'd like to publish the 0.7.0 release as an npm package.

- Update README with latest screenshot
- Review Wiki docs for correctness

**Comment by acrisci** [comment]
An npm package would be very beneficial to me as well 👍 . If your project doesn't want to support it, would you be opposed to a community-supported npm package?

**Comment by BoykoAlex** [comment]
We were planning to npm publish 0.7.0 at the end of the month.
There are a few things left to do:
* One last component to port - `code-editor` based on `CodeMirror`
* Possible upgrade to Angular 5 (if RxJS issues are addressed)

**Comment by BoykoAlex** [comment]
@acrisci as a workaround you can specify a specific commit in master branch of `spring-flo` in your dependencies until 0.7.0 is published...

**Comment by acrisci** [comment]
Ok is there any issue I can take to help speed this up?

**Comment by BoykoAlex** [comment]
@acrisci I've started working on that last component port... it can be tested mostly with our client app, but I was thinking also adding an example of it in the sample... This will take 1-2 days i think. Then we can npm publish 0.7.0. Early next week.

**Comment by BoykoAlex** [comment]
We'll put Angular 5 upgrade in 0.7.1 then.

**Comment by aruizp** [comment]
Any word on this?

**Comment by BoykoAlex** [comment]
@aruizp Releasing 0.7.0 today/tomorrow. Angular 5 upgrade is working but will go into 0.7.1.

**Comment by aruizp** [comment]
@BoykoAlex Thats great news, Thanks!

**Comment by BoykoAlex** [comment]
I have published `0.7.0-beta` to npm now. Please give it a quick try. We'll publish `0.7.0` tomorrow if everything goes well.

**Comment by acrisci** [comment]
I'm getting this mysterious build error since Friday afternoon. Has anyone ever seen this before?

<blockquote>
ERROR in Error: Error encountered resolving symbol values statically. Function calls are not supported. Consider replacing the function or lambda with a reference to an exported function (position 194:50 in the original .ts file), resolving symbol NgModule in project/node_modules/spring-flo/node_modules/@angular/core/core.d.ts, resolving symbol FloModule in project/node_modules/spring-flo/spring-flo.d.ts, resolving symbol FloModule in project/node_modules/spring-flo/spring-flo.d.ts
</blockquote>

**Comment by BoykoAlex** [comment]
@acrisci what is your Angular version in your client app?

**Comment by BoykoAlex** [comment]
@acrisci Any update? Try having Angular 4.4.6 in your client app...

**Comment by acrisci** [comment]
I updated to that version of angular and I am still having the same issue.

**Comment by BoykoAlex** [comment]
@acrisci Try pointing to git commit in your `package.json`, i.e the old way:
`"spring-flo": "git://github.com/spring-projects/spring-flo.git#fef3d96a594b04686b13c0f3835aa049596eb6ac"`
Check which commit works. If they all work. Try, building `spring-flo` by running `npm run build` and then point your `spring-flo` dependency at the `dist` folder with  file URL: `"spring-flo": "file:///Users/acrisci/spring-flo/dist"` (path is just for the sake of an example)

**Comment by BoykoAlex** [comment]
0.7.0 is published

**Comment by sabbyanandan** [comment]
Thanks, @BoykoAlex!
